services:

  node1:
    build:
      context: .
      target: production
    container_name: raft-node-1
    environment:
      NODE_ID: node1
      PORT: 5001
      PEERS: node2:5002,node3:5003
    ports:
      - "5001:5001"
    volumes:
      - ./data/node1:/app/data

  node2:
    build:
      context: .
      target: production
    container_name: raft-node-2
    environment:
      NODE_ID: node2
      PORT: 5002
      PEERS: node1:5001,node3:5003
    ports:
      - "5002:5002"
    volumes:
      - ./data/node2:/app/data

  node3:
    build:
      context: .
      target: production
    container_name: raft-node-3
    environment:
      NODE_ID: node3
      PORT: 5003
      PEERS: node1:5001,node2:5002
    ports:
      - "5003:5003"
    volumes:
      - ./data/node3:/app/data